---
script: "./script/cibuild"
gemfile: "this/does/not/exist"
rvm:
  - 1.8.7
  - 1.9.3
env:
  global:
    # encrypted GITHUB_API_TOKEN for librarian-puppet
    secure: owGmz4cdIVBnXHWdUR1poks2l1ijyp95+iD8gYngQ+1MbOpdaG8inEouqdm+Pk7/Og40bNiBgswLTBxmi/dGBW6Q7DBgRR9BEh5zSBKjeL9XFAObpAO2Gc/qAMfiu/BocQhYx8yOc/QagPV4NoTaMnBuldWT5bruJ2agV34rRWs=
